#!/usr/bin/env bash

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 image1 [image2 ...]"
  exit 1
fi

for img in "$@"; do
  if [ ! -f "$img" ]; then
    echo "File not found: $img"
    continue
  fi

  mime=$(file --mime-type -b "$img")


  echo "Copying '$img' as '$mime' to clipboard..."
  if [[ "$mime" == "image/jpeg" ]]; then
    magick "$img" png:- | wl-copy --type image/png
  else
    wl-copy --type "$mime" < "$img"
  fi
  exit 0
done

echo "No valid files provided."
