#!/usr/bin/env bash

OLD_IFS=$IFS
artist=$(playerctl metadata --format '{{ artist }}')
title=$(playerctl metadata --format '{{ title }}')
max=37

if [ ${#title} -gt 40 ]; then
	title="${title:0:max}..."
fi

IFS=','

artist_arr=($artist)
artist="${artist_arr[0]}"

IFS=$OLD_IFS

if [ -z "$artist" ] && [ -z "$title" ]; then
	echo "Not playing anyting right now"
else
	echo "$artist - $title"
fi
