#!/usr/bin/env bash

declare -A pomo_options
pomo_options["work"]="60m"
pomo_options["break"]="10m"

if [ -n "$1" ] && [ -n "${pomo_options["$1"]}" ]; then
  current_session=$1
  echo "$current_session" | lolcat
  timer "${pomo_options["$current_session"]}"

  # Display a Rofi menu with "continue" and "finish"
  session_name="Work"
  next_session_name="Break"
  if [ "$current_session" = "break" ]; then
    session_name="Break"
    next_session_name="Work"
  fi
  echo -e "\a"
  sleep 2
  echo -e "\a"
  user_choice=$(echo -e "Continue ($next_session_name)\nSkip\nFinish" | rofi -dmenu -p "$session_name session finished:")

  if [ "$user_choice" = "Continue ($next_session_name)" ]; then
    # Toggle session type: if current is work, next should be break; if current is break, next should be work.
    if [ "$current_session" = "work" ]; then
      next_session="break"
    else
      next_session="work"
    fi
    # Restart the script with the chosen next session type.
    exec "$0" "$next_session"
  elif [ "$user_choice" = "Finish" ]; then
    exit 0
  elif [ "$user_choice" = "Skip" ]; then
    exec "$0" "$current_session"
  fi
fi

